name = "thomas/agritrace"
version = "0.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'thomas/agritrace'"

[repository]
user = "thomas"
project = "agritrace"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"

[config]
